        <div class="container-fluid">
        <div class="row-fluid">
            <div class="row-fluid">
                <div class="span12" style="margin: auto;padding: auto;text-align: center;padding-top: 50px;">
                    <div class="alert  <?php if(isset($rs) && !empty($rs)) echo 'alert-error';else echo 'alert-info'?>">
                        <?php
                                if(isset($rs) && !empty($rs)) echo 'The username or password you entered is incorrect.';
                                else echo 'Please enter your Username and Password below.';
                        ?>
                    </div>
                    <form class="form-horizontal" action="" method="post">
                        <fieldset>
                            <div class="input-prepend" title="Username" data-rel="tooltip" style="padding-bottom: 10px;">
                                <span class="add-on"><i class="icon-user"></i></span><input autofocus class="input-large span10" name="username" id="username" type="text"/>
                            </div>
                            <div class="clearfix"></div>

                            <div class="input-prepend" title="Password" data-rel="tooltip">
                                <span class="add-on"><i class="icon-lock"></i></span><input class="input-large span10" name="password" id="password" type="password"/>
                            </div>
                            <div class="clearfix"></div>

                            <div class="input-prepend">
                            <label class="remember checkbox inline" for="remember"><input type="checkbox" id="rememberme" name="rememberme"/> Remember me</label>
                            </div>

                            <p class="center">
                            <button id="btnLogin" type="submit" class="btn btn-primary">Login</button>
                            </p>

                            <div class="clearfix"></div>
                            <p class="center">Can't access your account? <a href="#"> Reset password </a></p>
                        </fieldset>
                    </form>
                </div><!--/span-->
            </div><!--/row-->
                </div><!--/fluid-row-->

    </div><!--/.fluid-container-->