<div class="row">
<div class="span12">
<h1 class="title">About CS</h1>
We are business solutions specialists, assisting our clients to connect people to their projects...and their projects to their technology...their technology to their organisational processes...and their organisational processes back to their people.
<br>
<p>4impact has fast become recognised as one of Australia's most trusted and respected services companies, assisting clients in Brisbane, Sydney, Melbourne and Canberra. 4impact delivers real improvements to your business performance through the implementation of strategy and the delivery of business and technology projects.  </p>
<p>Our success is largely due to our single-minded focus to develop trusted and meaningful relationships with our client organisations to share knowledge, expertise and a passion to deliver measurable value.</p>
<p>Our team comes from a varied background and has substantial experience in a wide range of industry sectors, and we recognise the different needs that varying sizes and scales of client organisations bring. </p>

<p><em><strong>One size does not fit all.</strong></em>
  Our delivery of projects across the ICT, financial services, government, infrastructure, property, mining and utilities sectors has taught us that all organisations have varying needs - different approaches and different benefits are derived from the different solution paths.
<br>
</p>
</div>
</div>