<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Blog'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/blog.css')
                        ->prependStylesheet($this->basePath() . '/css/StickyNotes.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/custom.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>

        <div id="navigation">
        	<div class="container">
                        <ul class="nav-custom-link">
                            <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                            <li><a href="<?php echo $this->url('about') ?>"><?php echo $this->translate('About') ?></a></li>
                            <li><a href="<?php echo $this->url('contact') ?>"><?php echo $this->translate('Contact') ?></a></li>
                            <li><a href="<?php echo $this->url('album') ?>"><?php echo $this->translate('Album') ?></a></li>
                            <li><a href="<?php echo $this->url('stickynotes') ?>"><?php echo $this->translate('Sticky Notes') ?></a></li>
                            <li><a href="<?php echo $this->url('tuser') ?>"><?php echo $this->translate('TUser') ?></a></li>
                        </ul>
                        <div style="float: right;padding-top: 10px;font-weight: bold;"><span style="color:white;font-weight: bold;"><?php
                        echo $this->translate('Language');?></span><a style="padding-left: 15px;padding-right: 15px;" href="/?lang=vi">VN</a><a href="/?lang=en">US</a></div>
        	</div>
        </div>

        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2012 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?>
                Author by <a href="http://www.linkedin.com/pub/tri-van/50/903/946" target="_blank">Tri Van</a></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
