
<div class="row" style="padding-top: 50px;">
	<div class="span12">
	<h5>Avaiable Functions</h5>
	<ul>
		<li><a href="<?php echo $this->url("listgeoip");?>">Geoip Detected</a></li>
		<li><a href="/application/index/location">Location</a></li>
		<li><a href="/updatelang?lang=vi_VN">change language</a></li>
	</ul>
	</div>
</div>

<div id="carousel-container" class="container">
<div class="main-carousel">
    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" style="position: relative;">
      <div class="carousel-inner">
        <div class="item active">
        <div class="container carousel-item" style="background-image: url('../img/bootstrap-mdo-sfmoma-01.jpg');">
        </div>
          <div class="container">
            <div class="carousel-caption">
              <h1>People</h1>
              <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            </div>
          </div>
        </div>
        <div class="item">
          <div class="container carousel-item" style="background-image: url('../img/bootstrap-mdo-sfmoma-02.jpg');"></div>
          <div class="container">
            <div class="carousel-caption">
              <h1>Projects</h1>
              <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            </div>
          </div>
        </div>
        <div class="item">
          <div class="container carousel-item" style="background-image: url('../img/bootstrap-mdo-sfmoma-03.jpg');"></div>
          <div class="container">
            <div class="carousel-caption">
              <h1>Technology</h1>
              <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            </div>
          </div>
        </div>
        <div class="item">
          <div class="container">
              <div class="container carousel-item" style="background-image: url('../img/bootstrap-mdo-sfmoma-02.jpg');"></div>
          </div>
          <div class="container">
            <div class="carousel-caption">
              <h1>Organisation</h1>
              <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            </div>
          </div>
        </div>
      </div>
      <ul class="navigation-carousel" >
        <li class="people selector-carousel" style="height: 92px;">
            <a><span>People</span></a>
        </li>
        <li class="projects selector-carousel" style="height: 71px;">
            <a><span>Projects</span></a>
        </li>
        <li class="technology selector-carousel" style="height: 91px;">
            <a><span>Technology</span></a>
        </li>
        <li class="organisation selector-carousel" style="height: 110px;">
            <a><span>Organisation</span></a>
        </li>
      </ul>
    </div><!-- /.carousel -->
</div>
</div>

<div class="row">
    <div class="span4">
        <h2><?php echo $this->translate('Follow Development') ?></h2>
        <p><?php echo sprintf($this->translate('Zend Framework 2 is under active development. If you are interested in following the development of ZF2, there is a special ZF2 portal on the official Zend Framework website which provides links to the ZF2 %swiki%s, %sdev blog%s, %sissue tracker%s, and much more. This is a great resource for staying up to date with the latest developments!'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
    </div>
    <div class="span4">
        <h2><?php echo $this->translate('Discover Modules') ?></h2>
        <p><?php echo sprintf($this->translate('The community is working on developing a community site to serve as a repository and gallery for ZF2 modules. The project is available %son GitHub%s. The site is currently live and currently contains a list of some of the modules already available for ZF2.'), '<a href="https://github.com/zendframework/modules.zendframework.com">', '</a>') ?></p>
   </div>
   <div class="span4">
       <h2><?php echo $this->translate('Help &amp; Support') ?></h2>
       <p><?php echo sprintf($this->translate('If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
   </div>
</div>

<script type="text/javascript">
            $('#myCarousel').carousel({
                 interval: 15000
            });
            $(".people").click(function(){
                var item = 0;
                $('#myCarousel').carousel(item);
                return false;
            });
            $(".projects").click(function(){
                var item = 1;
                $('#myCarousel').carousel(item);
                return false;
            });
            $(".technology").click(function(){
                var item = 2;
                $('#myCarousel').carousel(item);
                return false;
            });
            $(".organisation").click(function(){
                var item = 3;
                $('#myCarousel').carousel(item);
                return false;
            });
                $('#carousel-container').live('swipeleft swiperight',function(event){
                    if (event.type == "swiperight") {
                        $("#myCarousel").carousel('next');
                    }
                    if (event.type == "swipeleft") {
                        $("#myCarousel").carousel('prev');
                    }
                    event.preventDefault();
                });
</script>