
<h2 style="padding-top: 50px;">Date/Time Picker for Twitter Boostrap</h2>
<div style="width: 100%;height: 500px;max-height: 500px;overflow: auto;">
<h3 id="demo">Demo</h3>

<h4 id="default_behavior_in_ptbr_picks_datetime_with_fast_masked_input_typing_need_only_to_type_the_numbers_the_static_part_of_the_mask_is_inserted_automatically_if_missing_or_via_the_popup_widget_which_supports_year_month_day_hour_and_minute_views">Default behavior in pt-BR, picks date/time with fast masked input typing (need only to type the numbers, the static part of the mask is inserted automatically if missing) or via the popup widget, which supports year, month, day, hour and minute views:</h4>
<div class="well">
  <div class="input-append date" id="datetimepicker1">
    <input data-format="dd/MM/yyyy hh:mm:ss" type="text">
    <span class="add-on">
      <i data-date-icon="icon-calendar" data-time-icon="icon-time" class="icon-calendar">
      </i>
    </span>
  </div>
</div><script type="text/javascript">
  $(function() {
    $('#datetimepicker1').datetimepicker({
      language: 'pt-BR'
    });
  });
</script>
<p>Code:</p>
<div class="highlight"><pre><code class="html"><span class="nt">&lt;div</span> <span class="na">class=</span><span class="s">"well"</span><span class="nt">&gt;</span>
  <span class="nt">&lt;div</span> <span class="na">id=</span><span class="s">"datetimepicker1"</span> <span class="na">class=</span><span class="s">"input-append date"</span><span class="nt">&gt;</span>
    <span class="nt">&lt;input</span> <span class="na">data-format=</span><span class="s">"dd/MM/yyyy hh:mm:ss"</span> <span class="na">type=</span><span class="s">"text"</span><span class="nt">&gt;&lt;/input&gt;</span>
    <span class="nt">&lt;span</span> <span class="na">class=</span><span class="s">"add-on"</span><span class="nt">&gt;</span>
      <span class="nt">&lt;i</span> <span class="na">data-time-icon=</span><span class="s">"icon-time"</span> <span class="na">data-date-icon=</span><span class="s">"icon-calendar"</span><span class="nt">&gt;</span>
      <span class="nt">&lt;/i&gt;</span>
    <span class="nt">&lt;/span&gt;</span>
  <span class="nt">&lt;/div&gt;</span>
<span class="nt">&lt;/div&gt;</span>
<span class="nt">&lt;script </span><span class="na">type=</span><span class="s">"text/javascript"</span><span class="nt">&gt;</span>
  <span class="nx">$</span><span class="p">(</span><span class="kd">function</span><span class="p">()</span> <span class="p">{</span>
    <span class="nx">$</span><span class="p">(</span><span class="s1">'#datetimepicker1'</span><span class="p">).</span><span class="nx">datetimepicker</span><span class="p">({</span>
      <span class="nx">language</span><span class="o">:</span> <span class="s1">'pt-BR'</span>
    <span class="p">});</span>
  <span class="p">});</span>
<span class="nt">&lt;/script&gt;</span>
</code></pre></div>
<h4 id="similar_to_above_example_but_in_us_datehour_format">Similar to above example, but in US date/hour format:</h4>
<div class="well">
  <div class="input-append" id="datetimepicker2">
    <input data-format="MM/dd/yyyy HH:mm:ss PP" type="text">
    <span class="add-on">
      <i data-date-icon="icon-calendar" data-time-icon="icon-time" class="icon-calendar">
      </i>
    </span>
  </div>
</div><script type="text/javascript">
  $(function() {
    $('#datetimepicker2').datetimepicker({
      language: 'en',
      pick12HourFormat: true
    });
  });
</script>
<p>Code:</p>
<div class="highlight"><pre><code class="html"><span class="nt">&lt;div</span> <span class="na">class=</span><span class="s">"well"</span><span class="nt">&gt;</span>
  <span class="nt">&lt;div</span> <span class="na">id=</span><span class="s">"datetimepicker2"</span> <span class="na">class=</span><span class="s">"input-append"</span><span class="nt">&gt;</span>
    <span class="nt">&lt;input</span> <span class="na">data-format=</span><span class="s">"MM/dd/yyyy HH:mm:ss PP"</span> <span class="na">type=</span><span class="s">"text"</span><span class="nt">&gt;&lt;/input&gt;</span>
    <span class="nt">&lt;span</span> <span class="na">class=</span><span class="s">"add-on"</span><span class="nt">&gt;</span>
      <span class="nt">&lt;i</span> <span class="na">data-time-icon=</span><span class="s">"icon-time"</span> <span class="na">data-date-icon=</span><span class="s">"icon-calendar"</span><span class="nt">&gt;</span>
      <span class="nt">&lt;/i&gt;</span>
    <span class="nt">&lt;/span&gt;</span>
  <span class="nt">&lt;/div&gt;</span>
<span class="nt">&lt;/div&gt;</span>
<span class="nt">&lt;script </span><span class="na">type=</span><span class="s">"text/javascript"</span><span class="nt">&gt;</span>
  <span class="nx">$</span><span class="p">(</span><span class="kd">function</span><span class="p">()</span> <span class="p">{</span>
    <span class="nx">$</span><span class="p">(</span><span class="s1">'#datetimepicker2'</span><span class="p">).</span><span class="nx">datetimepicker</span><span class="p">({</span>
      <span class="nx">language</span><span class="o">:</span> <span class="s1">'en'</span><span class="p">,</span>
      <span class="nx">pick12HourFormat</span><span class="o">:</span> <span class="kc">true</span>
    <span class="p">});</span>
  <span class="p">});</span>
<span class="nt">&lt;/script&gt;</span>
</code></pre></div>
<h4 id="disables_date_picker">Disables date picker:</h4>
<div class="well">
  <div class="input-append" id="datetimepicker3">
    <input data-format="hh:mm:ss" type="text">
    <span class="add-on">
      <i data-date-icon="icon-calendar" data-time-icon="icon-time" class="icon-time">
      </i>
    </span>
  </div>
</div><script type="text/javascript">
  $(function() {
    $('#datetimepicker3').datetimepicker({
      pickDate: false
    });
  });
</script>
<p>Code:</p>
<div class="highlight"><pre><code class="html"><span class="nt">&lt;div</span> <span class="na">class=</span><span class="s">"well"</span><span class="nt">&gt;</span>
  <span class="nt">&lt;div</span> <span class="na">id=</span><span class="s">"datetimepicker3"</span> <span class="na">class=</span><span class="s">"input-append"</span><span class="nt">&gt;</span>
    <span class="nt">&lt;input</span> <span class="na">data-format=</span><span class="s">"hh:mm:ss"</span> <span class="na">type=</span><span class="s">"text"</span><span class="nt">&gt;&lt;/input&gt;</span>
    <span class="nt">&lt;span</span> <span class="na">class=</span><span class="s">"add-on"</span><span class="nt">&gt;</span>
      <span class="nt">&lt;i</span> <span class="na">data-time-icon=</span><span class="s">"icon-time"</span> <span class="na">data-date-icon=</span><span class="s">"icon-calendar"</span><span class="nt">&gt;</span>
      <span class="nt">&lt;/i&gt;</span>
    <span class="nt">&lt;/span&gt;</span>
  <span class="nt">&lt;/div&gt;</span>
<span class="nt">&lt;/div&gt;</span>
<span class="nt">&lt;script </span><span class="na">type=</span><span class="s">"text/javascript"</span><span class="nt">&gt;</span>
  <span class="nx">$</span><span class="p">(</span><span class="kd">function</span><span class="p">()</span> <span class="p">{</span>
    <span class="nx">$</span><span class="p">(</span><span class="s1">'#datetimepicker3'</span><span class="p">).</span><span class="nx">datetimepicker</span><span class="p">({</span>
      <span class="nx">pickDate</span><span class="o">:</span> <span class="kc">false</span>
    <span class="p">});</span>
  <span class="p">});</span>
<span class="nt">&lt;/script&gt;</span>
</code></pre></div>
<h4 id="disables_time_picker">Disables time picker:</h4>
<div class="well">
  <div class="input-append" id="datetimepicker4">
    <input data-format="yyyy-MM-dd" type="text">
    <span class="add-on">
      <i data-date-icon="icon-calendar" data-time-icon="icon-time" class="icon-calendar">
      </i>
    </span>
  </div>
</div><script type="text/javascript">
  $(function() {
    $('#datetimepicker4').datetimepicker({
      pickTime: false
    });
  });
</script>
<p>Code:</p>
<div class="highlight"><pre><code class="html"><span class="nt">&lt;div</span> <span class="na">class=</span><span class="s">"well"</span><span class="nt">&gt;</span>
  <span class="nt">&lt;div</span> <span class="na">id=</span><span class="s">"datetimepicker4"</span> <span class="na">class=</span><span class="s">"input-append"</span><span class="nt">&gt;</span>
    <span class="nt">&lt;input</span> <span class="na">data-format=</span><span class="s">"yyyy-MM-dd"</span> <span class="na">type=</span><span class="s">"text"</span><span class="nt">&gt;&lt;/input&gt;</span>
    <span class="nt">&lt;span</span> <span class="na">class=</span><span class="s">"add-on"</span><span class="nt">&gt;</span>
      <span class="nt">&lt;i</span> <span class="na">data-time-icon=</span><span class="s">"icon-time"</span> <span class="na">data-date-icon=</span><span class="s">"icon-calendar"</span><span class="nt">&gt;</span>
      <span class="nt">&lt;/i&gt;</span>
    <span class="nt">&lt;/span&gt;</span>
  <span class="nt">&lt;/div&gt;</span>
<span class="nt">&lt;/div&gt;</span>
<span class="nt">&lt;script </span><span class="na">type=</span><span class="s">"text/javascript"</span><span class="nt">&gt;</span>
  <span class="nx">$</span><span class="p">(</span><span class="kd">function</span><span class="p">()</span> <span class="p">{</span>
    <span class="nx">$</span><span class="p">(</span><span class="s1">'#datetimepicker4'</span><span class="p">).</span><span class="nx">datetimepicker</span><span class="p">({</span>
      <span class="nx">pickTime</span><span class="o">:</span> <span class="kc">false</span>
    <span class="p">});</span>
  <span class="p">});</span>
<span class="nt">&lt;/script&gt;</span>
</code></pre></div>
<h3 id="api">API</h3>

<p>The widget class provides 4 methods to manipulate dates: ‘getDate’/’setDate’ for working with UTC and ‘getLocalDate’/’setLocalDate’ for working with local dates:</p>
<div class="highlight"><pre><code class="js"><span class="c1">// Considering you are on a GMT-3 timezone and the input contains '2000-01-17 10:00'</span>
<span class="kd">var</span> <span class="nx">localDate</span> <span class="o">=</span> <span class="nx">picker</span><span class="p">.</span><span class="nx">getLocalDate</span><span class="p">();</span> <span class="c1">// localDate === 2000-01-17 07:00</span>
<span class="kd">var</span> <span class="nx">utcDate</span> <span class="o">=</span> <span class="nx">picker</span><span class="p">.</span><span class="nx">getDate</span><span class="p">();</span> <span class="c1">// utcDate === 2000-01-17 10:00</span>
<span class="c1">//</span>
<span class="nx">picker</span><span class="p">.</span><span class="nx">setLocalDate</span><span class="p">(</span><span class="k">new</span> <span class="nb">Date</span><span class="p">(</span><span class="mi">1998</span><span class="p">,</span> <span class="mi">10</span><span class="p">,</span> <span class="mi">11</span><span class="p">,</span> <span class="mi">4</span><span class="p">,</span> <span class="mi">30</span><span class="p">));</span> <span class="c1">// input === 1998-10-11 07:30</span>
<span class="nx">picker</span><span class="p">.</span><span class="nx">setDate</span><span class="p">(</span><span class="k">new</span> <span class="nb">Date</span><span class="p">(</span><span class="nb">Date</span><span class="p">.</span><span class="nx">UTC</span><span class="p">(</span><span class="mi">1998</span><span class="p">,</span> <span class="mi">10</span><span class="p">,</span> <span class="mi">11</span><span class="p">,</span> <span class="mi">4</span><span class="p">,</span> <span class="mi">30</span><span class="p">)));</span> <span class="c1">// input === 1998-10-11 04:30</span>
</code></pre></div>
<p>The date value can be unset by passing ‘null’ to any of the ‘set’ methods or by erasing the input:</p>
<div class="highlight"><pre><code class="js"><span class="kd">var</span> <span class="nx">picker</span> <span class="o">=</span> <span class="nx">$</span><span class="p">(</span><span class="s1">'#datetimepicker'</span><span class="nx">l</span><span class="p">).</span><span class="nx">data</span><span class="p">(</span><span class="s1">'datetimepicker'</span><span class="p">);</span>
<span class="nx">picker</span><span class="p">.</span><span class="nx">setLocalDate</span><span class="p">(</span><span class="kc">null</span><span class="p">);</span>
<span class="c1">// or</span>
<span class="nx">picker</span><span class="p">.</span><span class="nx">setDate</span><span class="p">(</span><span class="kc">null</span><span class="p">);</span>
<span class="c1">// or</span>
<span class="nx">input</span><span class="p">.</span><span class="nx">val</span><span class="p">(</span><span class="s1">''</span><span class="p">);</span>
<span class="nx">input</span><span class="p">.</span><span class="nx">change</span><span class="p">();</span>
</code></pre></div>
<p>The only event exposed is ‘changeDate’, which will expose ‘date’ and ‘localDate’ properties on the event object:</p>
<div class="highlight"><pre><code class="js"><span class="nx">el</span><span class="p">.</span><span class="nx">on</span><span class="p">(</span><span class="s1">'changeDate'</span><span class="p">,</span> <span class="kd">function</span><span class="p">(</span><span class="nx">e</span><span class="p">)</span> <span class="p">{</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">e</span><span class="p">.</span><span class="nx">date</span><span class="p">.</span><span class="nx">toString</span><span class="p">());</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">e</span><span class="p">.</span><span class="nx">localDate</span><span class="p">.</span><span class="nx">toString</span><span class="p">());</span>
<span class="p">});</span>
</code></pre></div>
<h3 id="options">Options</h3>

<p>These are the default options for initializing the widget:</p>
<div class="highlight"><pre><code class="js"><span class="nx">$</span><span class="p">.</span><span class="nx">fn</span><span class="p">.</span><span class="nx">datetimepicker</span><span class="p">.</span><span class="nx">defaults</span> <span class="o">=</span> <span class="p">{</span>
  <span class="nx">maskInput</span><span class="o">:</span> <span class="kc">true</span><span class="p">,</span>           <span class="c1">// disables the text input mask</span>
  <span class="nx">pickDate</span><span class="o">:</span> <span class="kc">true</span><span class="p">,</span>            <span class="c1">// disables the date picker</span>
  <span class="nx">pickTime</span><span class="o">:</span> <span class="kc">true</span><span class="p">,</span>            <span class="c1">// disables de time picker</span>
  <span class="nx">pick12HourFormat</span><span class="o">:</span> <span class="kc">false</span><span class="p">,</span>   <span class="c1">// enables the 12-hour format time picker</span>
  <span class="nx">pickSeconds</span><span class="o">:</span> <span class="kc">true</span><span class="p">,</span>         <span class="c1">// disables seconds in the time picker</span>
  <span class="nx">startDate</span><span class="o">:</span> <span class="o">-</span><span class="kc">Infinity</span><span class="p">,</span>      <span class="c1">// set a minimum date</span>
  <span class="nx">endDate</span><span class="o">:</span> <span class="kc">Infinity</span>          <span class="c1">// set a maximum date</span>
<span class="p">};</span>
</code></pre></div>
<p>Examples of using these options can be seen in the file test/specs.coffee.</p>

<h3 id="complete_sample_markup">Complete sample markup</h3>

<p>Copy and paste the following code in a file(eg: test.html) and it should produce a widget similar to the first demo:</p>
<div class="highlight"><pre><code class="html"><span class="cp">&lt;!DOCTYPE HTML&gt;</span>
<span class="nt">&lt;html&gt;</span>
  <span class="nt">&lt;head&gt;</span>
    <span class="nt">&lt;link</span> <span class="na">href=</span><span class="s">"http://netdna.bootstrapcdn.com/twitter-bootstrap/2.2.2/css/bootstrap-combined.min.css"</span> <span class="na">rel=</span><span class="s">"stylesheet"</span><span class="nt">&gt;</span>
    <span class="nt">&lt;link</span> <span class="na">rel=</span><span class="s">"stylesheet"</span> <span class="na">type=</span><span class="s">"text/css"</span> <span class="na">media=</span><span class="s">"screen"</span>
     <span class="na">href=</span><span class="s">"http://tarruda.github.com/bootstrap-datetimepicker/assets/css/bootstrap-datetimepicker.min.css"</span><span class="nt">&gt;</span>
  <span class="nt">&lt;/head&gt;</span>
  <span class="nt">&lt;body&gt;</span>
    <span class="nt">&lt;div</span> <span class="na">id=</span><span class="s">"datetimepicker"</span> <span class="na">class=</span><span class="s">"input-append date"</span><span class="nt">&gt;</span>
      <span class="nt">&lt;input</span> <span class="na">type=</span><span class="s">"text"</span><span class="nt">&gt;&lt;/input&gt;</span>
      <span class="nt">&lt;span</span> <span class="na">class=</span><span class="s">"add-on"</span><span class="nt">&gt;</span>
        <span class="nt">&lt;i</span> <span class="na">data-time-icon=</span><span class="s">"icon-time"</span> <span class="na">data-date-icon=</span><span class="s">"icon-calendar"</span><span class="nt">&gt;&lt;/i&gt;</span>
      <span class="nt">&lt;/span&gt;</span>
    <span class="nt">&lt;/div&gt;</span>
    <span class="nt">&lt;script </span><span class="na">type=</span><span class="s">"text/javascript"</span>
     <span class="na">src=</span><span class="s">"http://cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.min.js"</span><span class="nt">&gt;</span>
    <span class="nt">&lt;/script&gt;</span>
    <span class="nt">&lt;script </span><span class="na">type=</span><span class="s">"text/javascript"</span>
     <span class="na">src=</span><span class="s">"http://netdna.bootstrapcdn.com/twitter-bootstrap/2.2.2/js/bootstrap.min.js"</span><span class="nt">&gt;</span>
    <span class="nt">&lt;/script&gt;</span>
    <span class="nt">&lt;script </span><span class="na">type=</span><span class="s">"text/javascript"</span>
     <span class="na">src=</span><span class="s">"http://tarruda.github.com/bootstrap-datetimepicker/assets/js/bootstrap-datetimepicker.min.js"</span><span class="nt">&gt;</span>
    <span class="nt">&lt;/script&gt;</span>
    <span class="nt">&lt;script </span><span class="na">type=</span><span class="s">"text/javascript"</span>
     <span class="na">src=</span><span class="s">"http://tarruda.github.com/bootstrap-datetimepicker/assets/js/bootstrap-datetimepicker.pt-BR.js"</span><span class="nt">&gt;</span>
    <span class="nt">&lt;/script&gt;</span>
    <span class="nt">&lt;script </span><span class="na">type=</span><span class="s">"text/javascript"</span><span class="nt">&gt;</span>
      <span class="nx">$</span><span class="p">(</span><span class="s1">'#datetimepicker'</span><span class="p">).</span><span class="nx">datetimepicker</span><span class="p">({</span>
        <span class="nx">format</span><span class="o">:</span> <span class="s1">'dd/MM/yyyy hh:mm:ss'</span><span class="p">,</span>
        <span class="nx">language</span><span class="o">:</span> <span class="s1">'pt-BR'</span>
      <span class="p">});</span>
    <span class="nt">&lt;/script&gt;</span>
  <span class="nt">&lt;/body&gt;</span>
<span class="nt">&lt;html&gt;</span>
</code></pre></div>
</div>